#!/bin/bash
# ============================================================
# Add a custom tenant domain to nginx + auto-issue Let's Encrypt SSL.
# ------------------------------------------------------------
# Usage:
#   ./scripts/add-domain.sh menu.catch.com
#   ./scripts/add-domain.sh menu.catch.com www.menu.catch.com
#
# What it does:
#   1. Verifies that DNS A-record of the domain points to THIS server.
#   2. Issues a Let's Encrypt certificate via certbot (webroot HTTP-01).
#   3. Writes an HTTPS server-block to nginx/custom-domains/DOMAIN.conf.
#      Files in this directory are OUTSIDE git (see .gitignore), so
#      `update.sh` (`git reset --hard`) никогда их не перетрёт — тенант-
#      домены остаются привязанными независимо от деплоев.
#   4. Validates full nginx config, then reloads nginx.
#
# Prerequisites:
#   - Run from the project root (where docker-compose.yml lives).
#   - DNS A-record must already point to this VPS (5–30 min propagation).
#   - In admin panel the same domain must be added to the target restaurant.
# ============================================================

set -e

if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <domain> [extra_domain ...]"
    echo "Example: $0 menu.catch.com"
    exit 1
fi

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

CUSTOM_DIR="$PROJECT_DIR/nginx/custom-domains"
NGINX_CONF="$PROJECT_DIR/nginx/nginx.conf"
DOMAIN="$1"
shift
EXTRA_DOMAINS="$@"
ALL_DOMAINS="$DOMAIN $EXTRA_DOMAINS"
DOMAIN_CONF="$CUSTOM_DIR/${DOMAIN}.conf"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}▶${NC} $1"; }
ok()   { echo -e "${GREEN}✓${NC} $1"; }
warn() { echo -e "${YELLOW}!${NC} $1"; }
err()  { echo -e "${RED}✗${NC} $1"; exit 1; }

mkdir -p "$CUSTOM_DIR"

# -------- 0. One-time migration: ensure nginx.conf has the include directive --------
if ! grep -q "include /etc/nginx/custom-domains" "$NGINX_CONF"; then
    err "В nginx.conf отсутствует директива 'include /etc/nginx/custom-domains/*.conf;'. Запустите git pull — нужен свежий nginx.conf."
fi

# -------- 1. Verify DNS points to this server --------
log "Проверяю DNS-запись для ${DOMAIN}..."
SERVER_IP=$(curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || \
            curl -fsS --max-time 5 https://ifconfig.me 2>/dev/null || \
            hostname -I | awk '{print $1}')
if [ -z "$SERVER_IP" ]; then
    warn "Не удалось определить публичный IP сервера. Пропускаю DNS-проверку."
else
    log "Публичный IP сервера: ${SERVER_IP}"
    DOMAIN_IPS=$(getent ahosts "$DOMAIN" 2>/dev/null | awk '{print $1}' | sort -u | tr '\n' ' ')
    if [ -z "$DOMAIN_IPS" ]; then
        err "DNS не отвечает для ${DOMAIN}. Создайте у регистратора A-запись: ${DOMAIN} → ${SERVER_IP} и подождите 5-30 минут."
    fi
    log "DNS вернул: ${DOMAIN_IPS}"
    if ! echo "$DOMAIN_IPS" | grep -qw "$SERVER_IP"; then
        err "Домен ${DOMAIN} указывает на ${DOMAIN_IPS}, а сервер имеет IP ${SERVER_IP}. Поправьте A-запись и подождите DNS-пропагацию."
    fi
    ok "DNS корректно указывает на этот сервер"
fi

# -------- 2. Make sure nginx is up (for ACME challenge on port 80) --------
log "Поднимаю nginx"
docker compose up -d nginx >/dev/null

# -------- 3. Issue certificate FIRST (so nginx -t later can find the files) --------
DOMAIN_ARGS=""
for d in $ALL_DOMAINS; do DOMAIN_ARGS="$DOMAIN_ARGS -d $d"; done

if [ -d "$PROJECT_DIR/nginx/ssl/live/$DOMAIN" ]; then
    warn "Сертификат для ${DOMAIN} уже существует. Пропускаю выпуск."
else
    log "Получаю SSL-сертификат Let's Encrypt для ${ALL_DOMAINS}"
    docker compose run --rm --entrypoint "\
        certbot certonly --webroot -w /var/www/certbot \
        --email admin@${DOMAIN} --agree-tos --no-eff-email \
        $DOMAIN_ARGS" certbot \
        || err "Certbot failed. Возможные причины: DNS не указывает на этот сервер, порт 80 закрыт, или Let's Encrypt rate limit."
    ok "Сертификат получен"
fi

# -------- 4. Write per-domain nginx config --------
if [ -f "$DOMAIN_CONF" ]; then
    warn "Конфиг ${DOMAIN_CONF} уже существует. Перезаписываю."
fi

log "Пишу конфиг ${DOMAIN_CONF}"
cat > "$DOMAIN_CONF" <<CONFEOF
# Auto-generated by scripts/add-domain.sh — не отслеживается git'ом.
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${ALL_DOMAINS};

    ssl_certificate /etc/nginx/ssl/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 20M;

    location /api/ {
        limit_req zone=api burst=20 nodelay;
        set \$backend_upstream "backend:8001";
        proxy_pass http://\$backend_upstream;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;
    }

    location / {
        set \$frontend_upstream "frontend:80";
        proxy_pass http://\$frontend_upstream;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
CONFEOF

# -------- 5. Validate full nginx config --------
log "Проверяю nginx -t..."
NGINX_TEST_OUTPUT=$(docker run --rm \
    -v "$NGINX_CONF":/etc/nginx/nginx.conf:ro \
    -v "$CUSTOM_DIR":/etc/nginx/custom-domains:ro \
    -v "$PROJECT_DIR/nginx/ssl":/etc/nginx/ssl:ro \
    nginx:alpine nginx -t -c /etc/nginx/nginx.conf 2>&1) || {
    echo "$NGINX_TEST_OUTPUT" | sed 's/^/  /'
    warn "Конфиг nginx после добавления ${DOMAIN} невалиден — удаляю файл."
    rm -f "$DOMAIN_CONF"
    err "Не удалось безопасно добавить домен. Конфиг откачен."
}
ok "Конфиг валиден"

# -------- 6. Reload nginx --------
log "Перезапускаю Nginx"
docker compose restart nginx >/dev/null

ok "Готово! Домен ${DOMAIN} подключён."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Что проверить:"
echo "  1. https://${DOMAIN}/api/health → {\"status\":\"ok\"}"
echo "  2. В админке нажмите «Проверить» рядом с этим доменом"
echo "  3. QR-код стола будет работать через новый домен"
echo ""
echo "Список подключённых доменов:"
ls -1 "$CUSTOM_DIR"/*.conf 2>/dev/null | xargs -n1 basename -s .conf 2>/dev/null || echo "  (пусто)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
